[package]
name = "get-idl"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-lang = "0.31.0"
solana-client = "2.2.6"
serde_json = "1.0"
solana-sdk = "2.2.2"
bincode = "2.0.1"
borsh = "0.10.3"
